#!/bin/bash

alias e='exit'

alias ssh='ssh -A'

alias lal='ls -al'

alias activate='source .env/bin/activate'

alias rg="rg --smart-case"

if [ -x /usr/local/bin/nvim ]; then
    alias vim='nvim'
fi
