#!/bin/bash
alias ipython='ipython-2.6'

# Use VIM as a pager for syntax-highlighting goodness
alias less='vim -u /usr/share/vim/vim72/macros/less.vim'

alias e='exit'

alias ssh='ssh -A'

alias lal='ls -al'

# Set up TERM variables.
# vt100 and xterm have no color in vim (at least on unixs), but if we call them xterm-color, they will.
# (vt100 for F-Secure SSH.)
# This may well be the case for some other terms, so I'm putting them here.
# Also set up a variable to indicate whether to set up the title functions.
# TODO gnome-terminal, or however it reports itself
case $TERM in

  screen)
    TERM_IS_COLOR=true
  ;;

  xterm-color|color_xterm|rxvt|Eterm|screen*) # screen.linux|screen-w
    TERM_IS_COLOR=true
  ;;

  linux)
    TERM_IS_COLOR=true
  ;;

  xterm|vt100)
    TERM_IS_COLOR=true
  ;;

  *xterm*|eterm|rxvt*)
    TERM_IS_COLOR=true
  ;;

  *)
    TERM_IS_COLOR=false
  ;;

esac

# dircolors... make sure that we have a color terminal, dircolors exists, and ls supports it.
if $TERM_IS_COLOR && ( grep --color=auto --help ) &> /dev/null; then
  alias ls="ls -FH"
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
else
  # No color, so put a slash at the end of directory names, etc. to differentiate.
  alias ls="ls -FH"
fi

