#!/bin/bash

if [ $YELPCODE ]; then
	ysql()
	{
		mysql -u yelpdev -h devdb1 -A yelp
	}

	log ()
	{
		tail -f ~/pg/yelp-main/logs/app.log
	}

	alog ()
	{
		tail -f ~/.httpd/logs/error.log
	}

	elog ()
	{
		tail -f ~/pg/yelp-main/logs/apperror.log
	}

	sb ()
	{
		if [ $YELP_IN_SANDBOX ]; then
			echo 'already in a sandbox';
		else
			sandbox --minimal -v bash -login;
		fi
	}

	sb-lucy ()
	{
		if [ $YELP_IN_SANDBOX ]; then
			echo 'already in a sandbox';
		else
			sandbox -v bash -login;
		fi
	}

	scribereader ()
	{
		~/pg/yelp-main/tools/scribereader $*
	}

	alias s3cmd='~/pg/yelp-main/aws/s3cmd/s3cmd-0.9.9.91/s3cmd'
	alias prod-scribereader="$HOME/pg/loc/tools/scribereader --host=scribe-prod.local.yelpcorp.com"
	alias stagea-scribereader="$HOME/pg/loc/tools/scribereader --host=stagea.local.yelpcorp.com"
	alias apperror-nagios='/nail/home/bryce/pg/loc/tools/scribereader --env=prod apperror | egrep '\''yelp/((billing|ordering)/|logic/(alacarte|billing|advertiser|credit_card))'\'' | /nail/home/bryce/pg/loc/tools/pretty_error_log | less -R'
	alias testify='testify -v --summary'
fi
